### PR TITLE
Added Connected() method

### PR DESCRIPTION
**Pull request by rocc0**
Hello, I switched from old version as you suggested, this version seams better but one useful method is missing. Can you add it? Thanks.

### CODE REVIEW

**Comment by FZambia** [comment]
How do you plan to use it? I am asking because in general this call is racy - you can ask for status and in next moment client can switch to disconnected state. So when your code under `if client.Connected()` statement will be executed you can meet a race when it's not `true` anymore. This can be normal actually if you handle errors and just want your code to work normally in most cases. So could you provide some context on how you are going to use this method?

**Comment by rocc0** [comment]
Here is a code:
```
		if c != nil {
			if !c.Connected() {
				log.Print("Reconnection to centrifuge")
				cn, err := newConnection(&centConfig, centConfig.DeviceID)
				if err != nil {
					return err
				}
				c = cn
			}
		} else {
			return errors.New("error")
		}
```
I need to disconnect client from cent when USB device is disconnected and reconnect to cent when device is connected again. There is a gap of time when device can be reconnected and connection to cent was not destroyed(some times USB device hangs when it invokes commands). Hence I need to check if connection is available to not create new, parallel connection.

**Comment by FZambia** [comment]
Can't you just reuse existing client calling its `Connect()`  and `Disconnect()` ([Disconnect](https://godoc.org/github.com/centrifugal/centrifuge-mobile#Client.Disconnect)) methods?

**Comment by rocc0** [comment]
After some analysis I realized that I mainly needed to unsubscribe from channels to avoid receiving commands. And of course, in production, there will be races (currently product is in dev state). Thanks for your last advice, it helped me to look wider on the situation :)

**Comment by FZambia** [comment]
Ah, right - subscribe/unsubscribe can be even better. Then waiting for you to try it out - maybe this pr won't be needed.

**Comment by rocc0** [comment]
I'm closing the PR as it not needed anymore, problem solved.

**Pull request closed without merging**
